"""Scriblark package boundaries with real files and ZIPs; no Windows claim."""

import copy
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest
import zipfile

try:
    import msix_qualification as msix
except ImportError:
    msix = None


def digest(data):
    return {"bytes": len(data), "sha256": hashlib.sha256(data).hexdigest()}


class PackageTests(unittest.TestCase):
    def setUp(self):
        self.assertIsNotNone(msix, "Scriblark MSIX qualification is not implemented")
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.root = Path(tmp.name).resolve()
        self.source = self.root / "source"
        self.release = self.root / "release"
        self.commit = "a" * 40
        self.inventory = self.root / "inputs.json"
        self.startup = self.root / "startup.json"
        actual = Path(__file__).resolve().parents[2]
        for relative in msix.SOURCE_FILES:
            target = self.source / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes((actual / relative).read_bytes())
        for relative in msix.REQUIRED_RELEASE_FILES:
            target = self.release / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            original = msix.SOURCE_COPIES.get(relative)
            target.write_bytes(
                (self.source / original).read_bytes()
                if original
                else (relative + " native fixture").encode()
            )
        # Use the actual retained originals, not strings generated by the
        # validator. Native inventory below observes these additional files.
        shutil.copytree(actual / "Release/notice-supplement/originals",
                        self.source / "Release/notice-supplement/originals")
        shutil.copytree(actual / "Release/notice-supplement/originals",
                        self.release / "share/inkquay/licenses/supplement/originals")
        self.artwork = self.source / "ui/pixmaps/com.trieflow.inkquay.png"
        self.native = self.source / "build/inkquay-windows-inventory.json"
        self.native.parent.mkdir(parents=True)
        files = msix.inventory_tree(self.release)
        prepared = json.loads((self.source / "Release/notice-supplement/SOURCE-INPUTS.json").read_text())
        self.owner = prepared["nativeOwners"][0]["package"]
        self.owner_version = prepared["nativeOwners"][0]["version"]
        rows = [
            {
                "path": name,
                **record,
                "package": self.owner,
                "packageVersion": self.owner_version,
            }
            for name, record in files.items()
        ]
        for row in rows:
            if row["path"] in ("bin/Scriblark.exe", "bin/Scriblark-wrapper.exe"):
                del row["package"]
                del row["packageVersion"]
        self.native.write_text(
            json.dumps(
                {
                    "schemaVersion": 3,
                    "sourceCommit": self.commit,
                    "platform": "win32",
                    "msystem": "MINGW64",
                    "packages": {self.owner: self.owner_version},
                    "files": rows,
                    "builtApplication": {"sha256": files["bin/Scriblark.exe"]["sha256"]},
                    "builtWrapper": {
                        "sha256": files["bin/Scriblark-wrapper.exe"]["sha256"]
                    },
                    "licenseAuditComplete": False,
                }
            )
        )
        self.refresh()

    def refresh(self):
        d = msix.create_input_inventory(self.release, self.source, self.commit)
        self.inventory.write_text(json.dumps(d))
        self.startup.write_text(
            json.dumps(
                {
                    "source_commit": self.commit,
                    "windows_native_startup": True,
                    "window_title": "Unsaved Document - Scriblark",
                    "executable_sha256": d["files"]["bin/Scriblark.exe"]["sha256"],
                    "package_inventory_sha256": digest(self.inventory.read_bytes())[
                        "sha256"
                    ],
                }
            )
        )

    def stage(self):
        return msix.stage_release(
            self.release,
            self.artwork,
            self.root / "stage",
            self.commit,
            self.inventory,
            self.startup,
            self.source,
        )

    def test_complete_stage_preserves_inputs_and_false_release_claims(self):
        d = self.stage()
        self.assertEqual(d["releaseInput"], msix.inventory_tree(self.release))
        self.assertEqual(d["payload"], msix.inventory_tree(self.root / "stage"))
        self.assertEqual(d["identity"]["executable"], "bin/Scriblark.exe")
        self.assertFalse(d["publicRelease"])
        self.assertFalse(d["licenseClearanceClaimed"])
        self.assertEqual(d["runtime"]["gtk"], "bin/libgtk-3-0.dll")

    def test_package_includes_original_native_cargo_and_rust_supplements(self):
        record = self.stage()
        prefix = "share/inkquay/licenses/supplement/"
        examples = {
            "originals/notice-supplement/mingw-w64-gmp/gmp-6.3.0/COPYING":
                "8ceb4b9ee5adedde47b31e975c1d90c73ad27b6b165a1dcd80c7c545eb65b903",
            "originals/cargo-inputs/upstream-notices/mutants-0.0.4/LICENSE":
                "479cbeb2506157776cf80abe31df18065d0fe50b5816ff77bfd75d5deb04ab5c",
            "originals/rust-runtime-notices/LICENSE-MIT":
                "b71bd43a069ca0641a9ecfe585ca7b3c53b5cc1608f8b68321168698e28b5ea1",
        }
        for relative, sha in examples.items():
            with self.subTest(relative=relative):
                self.assertIn(prefix + relative, record["payload"])
                self.assertEqual(record["payload"][prefix + relative]["sha256"], sha)
        self.assertIn(prefix + "SOURCE-INPUTS.json", record["payload"])

    def test_rehashed_stage_cannot_omit_or_change_original_supplements(self):
        prefix = "share/inkquay/licenses/supplement/"
        examples = (
            "originals/notice-supplement/mingw-w64-gmp/gmp-6.3.0/COPYING",
            "originals/cargo-inputs/upstream-notices/mutants-0.0.4/LICENSE",
            "originals/rust-runtime-notices/LICENSE-MIT",
            "SOURCE-INPUTS.json",
        )
        native_original = self.native.read_bytes()
        for relative in examples:
            name = prefix + relative
            target = self.release / name
            original = target.read_bytes()
            for replacement in (None, b"generic replacement notice"):
                with self.subTest(path=relative, missing=replacement is None):
                    if replacement is None:
                        target.unlink()
                    else:
                        target.write_bytes(replacement)
                    native = json.loads(native_original)
                    native["files"] = [row for row in native["files"] if row["path"] != name]
                    if replacement is not None:
                        native["files"].append({"path": name, **digest(replacement)})
                    self.native.write_text(json.dumps(native))
                    with self.assertRaisesRegex(ValueError, "Missing|notice/artwork"):
                        msix.create_input_inventory(self.release, self.source, self.commit)
                    target.write_bytes(original)
        self.native.write_bytes(native_original)

    def test_notice_index_requires_complete_unique_safe_exact_originals(self):
        index_path = self.source / "Release/notice-supplement/NOTICE-INDEX.json"
        original = index_path.read_bytes()
        for kind in ("missing-row", "duplicate", "traversal", "wrong-hash"):
            with self.subTest(kind=kind):
                index = json.loads(original)
                if kind == "missing-row":
                    index["files"].pop()
                    index["fileCount"] -= 1
                elif kind == "duplicate":
                    index["files"].append(dict(index["files"][0]))
                    index["fileCount"] += 1
                elif kind == "traversal":
                    index["files"][0]["path"] = "originals/../../outside"
                else:
                    index["files"][0]["sha256"] = "0" * 64
                index_path.write_text(json.dumps(index))
                with self.assertRaises(ValueError):
                    msix.copy_notice_supplement(self.source, self.root / kind)
                self.assertFalse((self.root / kind).exists())
        index_path.write_bytes(original)

    def test_notice_copy_rejects_changed_missing_or_linked_source_before_output(self):
        target = self.source / "Release/notice-supplement/originals/rust-runtime-notices/LICENSE-MIT"
        original = target.read_bytes()
        for kind in ("changed", "missing"):
            with self.subTest(kind=kind):
                if kind == "changed":
                    target.write_bytes(b"substituted source notice")
                else:
                    target.unlink()
                with self.assertRaises(ValueError):
                    msix.copy_notice_supplement(self.source, self.root / kind)
                self.assertFalse((self.root / kind).exists())
                target.write_bytes(original)
        outside = self.root / "outside-notice"
        outside.write_bytes(original)
        target.unlink()
        try:
            target.symlink_to(outside)
        except OSError as error:
            self.skipTest(f"Host cannot create source symlink: {error}")
        with self.assertRaisesRegex(ValueError, "Symlink/reparse"):
            msix.copy_notice_supplement(self.source, self.root / "linked")
        self.assertFalse((self.root / "linked").exists())
        self.assertEqual(outside.read_bytes(), original)

    def test_actual_notice_copy_command_preserves_all_bytes_and_prior_destination(self):
        actual = Path(__file__).resolve().parents[2]
        commands = [line for line in (actual / "windows-setup/package.sh").read_text().splitlines()
                    if line.startswith('python "$script_dir/../script/msix/copy_notice_supplement.py"')]
        self.assertEqual(len(commands), 1, "Actual Windows staging must invoke the checked notice copy")
        stage = self.root / "notice stage with spaces"
        stage.mkdir()
        unrelated = stage / "existing.txt"
        unrelated.write_bytes(b"preserve unrelated content")
        if sys.platform == "win32":
            bash = Path(sys.executable).resolve().parents[2] / "usr/bin/bash.exe"
            self.assertTrue(bash.is_file(), "Expected the qualified MSYS2 bash")
            setup = 'script_dir=$(cygpath -u "$1"); setup_dir=$(cygpath -u "$2"); python_executable=$(cygpath -u "$3"); '
        else:
            bash = "bash"
            setup = 'script_dir=$1; setup_dir=$2; python_executable=$3; '
        command = [str(bash), "-c", setup + commands[0].replace("python ", '"$python_executable" ', 1),
                   "notice-copy", str(actual / "windows-setup"), str(stage), sys.executable]
        subprocess.run(command, check=True, capture_output=True, text=True)
        expected = msix.inventory_tree(actual / "Release/notice-supplement")
        copied = stage / "share/inkquay/licenses/supplement"
        self.assertEqual(msix.inventory_tree(copied), expected)
        empty = copied / "originals/notice-supplement/mingw-w64-djvulibre/djvulibre-3.5.30/AUTHORS"
        self.assertEqual(empty.read_bytes(), b"")
        source_index = json.loads((copied / "SOURCE-INPUTS.json").read_text())
        self.assertEqual(source_index["sourceUrl"], "https://scriblark.trieflow.com/source")
        self.assertEqual(len(source_index["nativeOwners"]), 66)
        self.assertEqual(len(source_index["cargo"]["sources"]), 359)
        rerun = subprocess.run(command, capture_output=True, text=True)
        self.assertNotEqual(rerun.returncode, 0)
        self.assertIn("preserving prior bytes", rerun.stderr)
        self.assertEqual(msix.inventory_tree(copied), expected)
        self.assertEqual(unrelated.read_bytes(), b"preserve unrelated content")

    def test_current_mingw64_winpthread_owner_requires_exact_retained_version(self):
        # Run 34685959483 stopped on this actual owner/version before any
        # installed application test. The file contents here remain fixtures.
        package = "mingw-w64-x86_64-libwinpthread"
        current = "14.0.0.r375.g9c1abbbf5-1"
        runtime = self.release / "bin/libwinpthread-1.dll"
        runtime.write_bytes(b"MINGW64 runtime fixture, not a native binary")
        native = json.loads(self.native.read_text())
        native["files"].append({"path": "bin/libwinpthread-1.dll", **digest(runtime.read_bytes())})
        self.native.write_text(json.dumps(native))
        for version in (current, "14.0.0.r353.g6df76fa52-2", "99.0-unretained"):
            with self.subTest(version=version):
                native = json.loads(self.native.read_text())
                native["packages"][package] = version
                row = next(row for row in native["files"]
                           if row["path"] == "bin/libwinpthread-1.dll")
                row.update(package=package, packageVersion=version)
                self.native.write_text(json.dumps(native))
                if version == current:
                    self.refresh()
                    record = self.stage()
                    copied = "share/inkquay/licenses/supplement/SOURCE-INPUTS.json"
                    self.assertEqual(record["payload"][copied],
                                     digest((self.source / msix.NOTICE_SOURCE / "SOURCE-INPUTS.json").read_bytes()))
                    self.assertFalse(record["publicRelease"])
                    self.assertFalse(record["licenseClearanceClaimed"])
                else:
                    with self.assertRaisesRegex(ValueError, "retained source"):
                        msix.create_input_inventory(self.release, self.source, self.commit)

    def test_winpthread_supplement_binds_mingw64_recipe_and_direct_published_source(self):
        index = json.loads((self.source / msix.NOTICE_SOURCE / "SOURCE-INPUTS.json").read_text())
        owners = [row for row in index["nativeOwners"]
                  if row["package"] == "mingw-w64-x86_64-libwinpthread"]
        self.assertEqual(len(owners), 1)
        owner = owners[0]
        self.assertEqual(owner["version"], "14.0.0.r375.g9c1abbbf5-1")
        # This is the MINGW64 archive from the actual run, not TintFable's
        # different CLANG64 binary that shares the same preferred-form source.
        self.assertEqual(owner["binaryArchive"],
                         "mingw-w64-x86_64-libwinpthread-14.0.0.r375.g9c1abbbf5-1-any.pkg.tar.zst")
        self.assertEqual(owner["binaryArchiveSha256"],
                         "1d0ed7fda332a5c879de210f3d72c75fa1f3df7cc63dd951e763dec8eb02c1ee")
        sources = [row for row in index["nativeSourceArchives"]
                   if row["filename"] == owner["sourceArchive"]]
        self.assertEqual(len(sources), 1)
        source = sources[0]
        self.assertEqual(source["pkgbase"], owner["pkgbase"])
        self.assertEqual(source["version"], owner["version"])
        self.assertEqual(source["recipeSha256"], owner["binaryRecipeHash"])
        self.assertEqual(source["recipeSha256"],
                         "7e5cec4463bd044cddeeb584dc6aab3e91dee5afd088d382e90c6232d0dd4e17")
        self.assertEqual(source["bytes"], 54173752)
        self.assertEqual(source["sha256"],
                         "7bf513784ae0bc4f1a413e1f787f7a3ba2bd7ec0503980ea4d17ddf0e4796c87")
        self.assertEqual(source["delivery"]["kind"], "published_source_asset")
        self.assertEqual(source["delivery"]["url"],
                         "https://github.com/hashfunction/pixelquay/releases/download/"
                         "native-sources-2026-09-12-tintfable/" + source["filename"])
        self.assertEqual(set(source["delivery"]), {"kind", "url", "verifiedAtUtc"})
        self.assertNotIn("sourceMetadataPath", source)
        evidence = source["supplementEvidence"]
        self.assertEqual(evidence["binaryMetadata"]["pkgbuildSha256sum"], source["recipeSha256"])
        self.assertEqual(evidence["runtime"], {
            "path": "bin/libwinpthread-1.dll", "bytes": 63840,
            "sha256": "2da71960a872bd1e59b60377f798f285ce630106509d6bd1d75e553f16218b7b"})
        self.assertEqual(evidence["copiedNotice"]["bytes"], 2883)
        self.assertEqual(evidence["copiedNotice"]["sha256"],
                         "63263614cdd29f2f93cba85e992f041b31f9fc7b4033692f31269489a8a1b177")
        self.assertEqual(index["collection"]["manifestSha256"],
                         "4e6aa5ecac3e97a52c50e620957df32fa757aa718a0f4894bec36376728bfee5")
        self.assertEqual(index["collection"]["baselineQualificationRun"], 34641324772)
        self.assertEqual(evidence["supersededSourceArchive"],
                         "mingw-w64-winpthreads-14.0.0.r353.g6df76fa52-2.src.tar.zst")

    def test_source_index_rejects_a_different_coherently_recorded_native_version(self):
        native = json.loads(self.native.read_text())
        native["packages"][self.owner] = "99.0-unretained"
        for row in native["files"]:
            if row.get("package") == self.owner:
                row["packageVersion"] = "99.0-unretained"
        self.native.write_text(json.dumps(native))
        with self.assertRaisesRegex(ValueError, "retained source"):
            msix.create_input_inventory(self.release, self.source, self.commit)

    def test_native_inventory_rejects_missing_extra_duplicate_and_changed_files(self):
        original = self.native.read_text()
        for kind in (
            "missing",
            "extra",
            "duplicate",
            "changed",
            "wrong-source",
            "wrong-version",
            "unowned",
            "wrong-build",
        ):
            with self.subTest(kind=kind):
                d = json.loads(original)
                if kind == "missing":
                    d["files"].pop()
                elif kind == "extra":
                    d["files"].append(
                        {
                            "path": "bin/extra.dll",
                            **digest(b"fake"),
                            "package": self.owner,
                            "packageVersion": self.owner_version,
                        }
                    )
                elif kind == "duplicate":
                    d["files"].append(dict(d["files"][0]))
                elif kind == "changed":
                    d["files"][0]["sha256"] = "0" * 64
                elif kind == "wrong-source":
                    d["sourceCommit"] = "b" * 40
                elif kind == "wrong-version":
                    d["packages"][self.owner] = "2.0"
                elif kind == "unowned":
                    row = next(
                        r for r in d["files"] if r["path"] == "bin/libgtk-3-0.dll"
                    )
                    del row["package"]
                else:
                    d["builtWrapper"]["sha256"] = "0" * 64
                self.native.write_text(json.dumps(d))
                with self.assertRaises(ValueError):
                    msix.create_input_inventory(self.release, self.source, self.commit)
        self.native.write_text(original)

    def test_original_notice_and_artwork_changes_are_rejected(self):
        for staged, source in msix.SOURCE_COPIES.items():
            with self.subTest(source=source):
                p = self.release / staged
                old = p.read_bytes()
                p.write_bytes(b"changed")
                with self.assertRaises(ValueError):
                    msix.create_input_inventory(self.release, self.source, self.commit)
                p.write_bytes(old)

    def test_detailed_upstream_attribution_is_preserved_and_required(self):
        relative = "share/inkquay/licenses/copyright.txt"
        original = Path(__file__).resolve().parents[2] / "copyright.txt"
        expected = original.read_bytes()
        self.assertIn(b"Nararyans R.I.", expected)
        self.assertIn(b"Lucide Contributors", expected)
        self.assertIn(b"CC-BY-SA-4.0", expected)
        self.assertEqual((self.release / relative).read_bytes(), expected)
        package, record = self.package()
        self.assertEqual(record["sourceInputs"]["copyright.txt"], digest(expected))
        with zipfile.ZipFile(package) as archive:
            self.assertEqual(archive.read(relative), expected)

        # Neither a missing notice nor a consistently rehashed generic GPL
        # summary may replace the detailed copyright and asset attribution.
        for replacement in (None, (self.source / "debian/copyright").read_bytes()):
            with self.subTest(replacement="missing" if replacement is None else "generic"):
                target = self.release / relative
                if replacement is None:
                    target.unlink()
                else:
                    target.write_bytes(replacement)
                native = json.loads(self.native.read_text())
                native["files"] = [r for r in native["files"] if r["path"] != relative]
                if replacement is not None:
                    native["files"].append({"path": relative, **digest(replacement)})
                self.native.write_text(json.dumps(native))
                with self.assertRaisesRegex(ValueError, "Missing|notice/artwork"):
                    msix.create_input_inventory(self.release, self.source, self.commit)

    def test_actual_package_notice_copy_preserves_detailed_source_bytes(self):
        actual = Path(__file__).resolve().parents[2]
        script = (actual / "windows-setup/package.sh").read_text()
        copy_commands = [
            line for line in script.splitlines()
            if line.startswith('cp "$script_dir/../LICENSE"')
        ]
        self.assertEqual(len(copy_commands), 1)
        setup = self.root / "package stage with spaces"
        destination = setup / "share/inkquay/licenses"
        destination.mkdir(parents=True)
        # Run the actual source-notice copy command with only its input/output
        # directories adapted; do not run native package/build work on macOS.
        if sys.platform == "win32":
            # The qualification records the MINGW64 Python executable. Select
            # that same MSYS2 installation's bash, never a PATH WSL launcher.
            bash = Path(sys.executable).resolve().parents[2] / "usr/bin/bash.exe"
            self.assertTrue(bash.is_file(), "Expected the qualified MSYS2 bash")
            directories = 'script_dir=$(cygpath -u "$1"); setup_dir=$(cygpath -u "$2"); '
        else:
            bash = "bash"
            directories = 'script_dir=$1; setup_dir=$2; '
        subprocess.run(
            [str(bash), "-c", directories + copy_commands[0],
             "notice-copy", str(actual / "windows-setup"), str(setup)],
            check=True,
        )
        for name, source in (("copyright", "debian/copyright"), ("copyright.txt", "copyright.txt")):
            self.assertEqual((destination / name).read_bytes(), (actual / source).read_bytes())

    def test_startup_source_title_inventory_and_executable_are_bound(self):
        old = self.startup.read_text()
        for key, value in [
            ("source_commit", "b" * 40),
            ("window_title", "Xournal++"),
            ("package_inventory_sha256", "0" * 64),
            ("executable_sha256", "0" * 64),
            ("windows_native_startup", False),
        ]:
            d = json.loads(old)
            d[key] = value
            self.startup.write_text(json.dumps(d))
            with self.assertRaises(ValueError):
                self.stage()
        self.startup.write_text(old)

    def test_existing_stage_preserves_previous_bytes(self):
        p = self.root / "stage"
        p.mkdir()
        (p / "old").write_bytes(b"old")
        with self.assertRaises(ValueError):
            self.stage()
        self.assertEqual((p / "old").read_bytes(), b"old")

    def test_stage_mutation_after_receipt_is_rejected(self):
        (self.release / "extra.txt").write_bytes(b"extra")
        with self.assertRaises(ValueError):
            self.stage()

    def test_manifest_identity_and_capability_are_semantic(self):
        data = msix.create_manifest()
        msix.validate_manifest(data)
        for old, new in [
            (b"CN=InkQuay-CI-Qualification", b"CN=Other"),
            (b"bin/Scriblark.exe", b"bin/other.exe"),
            (b"runFullTrust", b"internetClient"),
        ]:
            self.assertIn(old, data)
            with self.assertRaises(ValueError):
                msix.validate_manifest(data.replace(old, new))

    def test_zip_and_unpacked_byte_verification(self):
        record = self.stage()
        stage = self.root / "stage"
        p = self.root / "test.msix"
        with zipfile.ZipFile(p, "w") as z:
            for name in record["payload"]:
                z.write(stage / name, name)
            z.writestr("AppxBlockMap.xml", b"metadata")
            z.writestr("[Content_Types].xml", b"metadata")
        self.assertEqual(
            msix.verify_msix(p, record["payload"])["verifiedPayloadFiles"],
            len(record["payload"]),
        )
        msix.verify_unpacked(stage, record["payload"])
        with zipfile.ZipFile(p, "a") as z:
            z.writestr("bin/unexpected.dll", b"foreign")
        with self.assertRaises(ValueError):
            msix.verify_msix(p, record["payload"])

    def test_windows_path_alias_and_traversal_rejection(self):
        for p in (
            "../escape",
            "bin/CON.dll",
            "bin/with.",
            "bin/with ",
            "C:/file",
            "bin/a:b",
        ):
            with self.assertRaises(ValueError):
                msix._checked_path(p)
        seen = {}
        msix._register_path("bin/A.dll", seen)
        with self.assertRaises(ValueError):
            msix._register_path("bin/a.dll", seen)

    def package(self):
        record = self.stage()
        path = self.root / "fixture.msix"
        with zipfile.ZipFile(path, "w") as archive:
            for relative in record["payload"]:
                archive.write(self.root / "stage" / relative, relative)
            archive.writestr("[Content_Types].xml", "<Types/>")
            archive.writestr("AppxBlockMap.xml", "<BlockMap/>")
        record["unpackedVerification"] = msix.verify_unpacked(
            self.root / "stage", record["payload"]
        )
        return path, record

    def test_exact_container_and_unpacked_payload_match(self):
        package, record = self.package()
        self.assertEqual(
            msix.verify_msix(package, record["payload"])["verifiedPayloadFiles"],
            len(record["payload"]),
        )
        self.assertEqual(
            msix.verify_unpacked(self.root / "stage", record["payload"])[
                "verifiedPayloadFiles"
            ],
            len(record["payload"]),
        )

    def test_installed_inventory_allows_only_signature_metadata_beyond_payload(self):
        record = self.stage()
        stage = self.root / "stage"
        (stage / "AppxSignature.p7x").write_bytes(b"ephemeral signing metadata fixture")
        self.assertEqual(
            msix.verify_installed(stage, record["payload"])["verifiedPayloadFiles"],
            len(record["payload"]),
        )
        (stage / "unexpected-resource.txt").write_bytes(
            b"unrecorded installed resource"
        )
        with self.assertRaises(ValueError):
            msix.verify_installed(stage, record["payload"])

    def test_install_preflight_rejects_coherently_rehashed_package_record(self):
        package, record = self.package()
        record_path = self.root / "package-record.json"
        record["containerVerification"] = msix.verify_msix(package, record["payload"])
        record_path.write_text(json.dumps(record))
        self.assertTrue(
            msix.verify_record_inputs(
                package,
                record_path,
                self.release,
                self.artwork,
                self.commit,
                self.inventory,
                self.startup,
                self.source,
            )
        )
        # An internally consistent hash/record cannot substitute another input revision.
        record["sourceCommit"] = "b" * 40
        record_path.write_text(json.dumps(record))
        with self.assertRaises(ValueError):
            msix.verify_record_inputs(
                package,
                record_path,
                self.release,
                self.artwork,
                self.commit,
                self.inventory,
                self.startup,
                self.source,
            )
        record["sourceCommit"] = self.commit
        record["runtime"] = {}
        record_path.write_text(json.dumps(record))
        with self.assertRaises(ValueError):
            msix.verify_record_inputs(
                package,
                record_path,
                self.release,
                self.artwork,
                self.commit,
                self.inventory,
                self.startup,
                self.source,
            )

    def test_opc_decodes_once_and_accepts_exact_bytes(self):
        package, record = self.package()
        for encoded, decoded in [
            ("libc%2B%2B.dll", "libc++.dll"),
            ("literal%2520.txt", "literal%20.txt"),
            ("R%C3%A9sum%C3%A9.txt", "Résumé.txt"),
        ]:
            data = b"fixture bytes"
            with zipfile.ZipFile(package, "a") as archive:
                archive.writestr(encoded, data)
            record["payload"][decoded] = digest(data)
        msix.verify_msix(package, record["payload"])

    def test_opc_alias_traversal_bad_utf8_and_special_paths_rejected(self):
        package, record = self.package()
        for name in (
            "bin/%69nkquay.exe",
            "BIN/INKQUAY.EXE",
            "_internal%2fescape.dll",
            "_internal%5cescape.dll",
            "%2e%2e/escape",
            "/absolute",
            "C:evil",
            "x%FF",
            "x%GG",
            "x%00",
            "CON.txt",
            "name.",
            "empty//name",
        ):
            changed = self.root / "changed.msix"
            shutil.copyfile(package, changed)
            with zipfile.ZipFile(changed, "a") as archive:
                archive.writestr(name, b"extra")
            with self.subTest(name=name), self.assertRaises(ValueError):
                msix.verify_msix(changed, record["payload"])

    def test_zip_link_and_unexpected_empty_directory_rejected(self):
        package, record = self.package()
        for name, mode in [("redirect", 0o120777), ("unreviewed/", 0o40755)]:
            changed = self.root / "changed.msix"
            shutil.copyfile(package, changed)
            info = zipfile.ZipInfo(name)
            info.external_attr = mode << 16
            with zipfile.ZipFile(changed, "a") as archive:
                archive.writestr(info, b"")
            with self.assertRaises(ValueError):
                msix.verify_msix(changed, record["payload"])

    def test_manifest_semantics_independent_of_coherent_hashes(self):
        package, record = self.package()
        for before, after in [
            (b"runFullTrust", b"internetClient"),
            (b"bin/Scriblark.exe", b"other.exe"),
            (b"CN=InkQuay-CI-Qualification", b"CN=foreign"),
        ]:
            data = (
                (self.root / "stage/AppxManifest.xml")
                .read_bytes()
                .replace(before, after)
            )
            with self.assertRaises(ValueError):
                msix.validate_manifest(data)
        root = self.root / "stage"
        (root / "AppxManifest.xml").write_bytes(data)
        record["payload"]["AppxManifest.xml"] = digest(data)
        with self.assertRaises(ValueError):
            msix.verify_unpacked(root, record["payload"])

    def test_exact_sdk_semantic_pack_unpack_and_tool_integrity(self):
        sdk = self.root / "Windows Kits/10/bin/10.0.26100.0/x64"
        sdk.mkdir(parents=True)
        tool = sdk / "makeappx.exe"
        tool.write_bytes(b"fixture tool")
        commands = []

        def runner(command):
            commands.append(command)
            p = Path(command[command.index("/p") + 1])
            d = Path(command[command.index("/d") + 1])
            if command[1] == "pack":
                with zipfile.ZipFile(p, "w") as z:
                    for f in d.rglob("*"):
                        if f.is_file():
                            z.write(f, f.relative_to(d).as_posix())
                    z.writestr("[Content_Types].xml", "<Types/>")
                    z.writestr("AppxBlockMap.xml", "<BlockMap/>")
            else:
                with zipfile.ZipFile(p) as z:
                    z.extractall(d)

        output = self.root / "package-output"
        msix.build_qualification(
            self.release,
            self.artwork,
            self.commit,
            tool,
            "10.0.26100.0",
            output,
            self.inventory,
            self.startup,
            self.source,
            runner,
        )
        self.assertEqual([c[1] for c in commands], ["pack", "unpack"])
        self.assertNotIn("/nv", commands[0])
        self.assertNotIn("/o", commands[0])
        self.assertIn("/v", commands[0])
        record = json.loads((output / "package-record.json").read_text())
        self.assertFalse(record["signed"])
        self.assertFalse(record["installationQualificationPassed"])
        self.assertEqual(
            record["makeAppx"]["sha256"], digest(tool.read_bytes())["sha256"]
        )
        with self.assertRaises(ValueError):
            msix._tool_record(tool, "10.0.22621.0")

    def test_sdk_tool_change_aborts_without_publishing_output(self):
        sdk = self.root / "Windows Kits/10/bin/10.0.26100.0/x64"
        sdk.mkdir(parents=True)
        tool = sdk / "makeappx.exe"
        tool.write_bytes(b"original SDK tool")

        def changing_tool(command):
            tool.write_bytes(b"changed SDK tool")

        output = self.root / "package-output"
        with self.assertRaisesRegex(ValueError, "MakeAppx changed"):
            msix.build_qualification(
                self.release,
                self.artwork,
                self.commit,
                tool,
                "10.0.26100.0",
                output,
                self.inventory,
                self.startup,
                self.source,
                changing_tool,
            )
        self.assertFalse(output.exists())

    def test_install_preflight_requires_exact_typed_unpack_evidence(self):
        package, record = self.package()
        record["containerVerification"] = msix.verify_msix(package, record["payload"])
        record_path = self.root / "package-record.json"
        count = len(record["payload"])
        for value in [
            None,
            {},
            {"verifiedPayloadFiles": 0},
            {"verifiedPayloadFiles": str(count)},
            {"verifiedPayloadFiles": float(count)},
            {"verifiedPayloadFiles": True},
            {"verifiedPayloadFiles": count, "unexpected": True},
        ]:
            with self.subTest(value=value):
                altered = copy.deepcopy(record)
                if value is None:
                    del altered["unpackedVerification"]
                else:
                    altered["unpackedVerification"] = value
                record_path.write_text(json.dumps(altered))
                with self.assertRaisesRegex(ValueError, "unpack"):
                    msix.verify_record_inputs(
                        package,
                        record_path,
                        self.release,
                        self.artwork,
                        self.commit,
                        self.inventory,
                        self.startup,
                        self.source,
                    )

    def test_different_valid_artwork_cannot_replace_source_artwork(self):
        alternative = self.root / "other.png"
        alternative.write_bytes(msix.resize_png(self.artwork.read_bytes(), 50))
        self.assertNotEqual(
            digest(alternative.read_bytes()), digest(self.artwork.read_bytes())
        )
        with self.assertRaisesRegex(ValueError, "artwork"):
            msix.stage_release(
                self.release,
                alternative,
                self.root / "stage",
                self.commit,
                self.inventory,
                self.startup,
                self.source,
            )


if __name__ == "__main__":
    unittest.main()
